<?php echo e(getCurrentLang()); ?>

<ul id="menu" class="page-sidebar-menu">
    <?php
        $user = $user = Sentinel::getuser();
        if($user['type']*1 == 99){ ?>
            <?php echo $__env->make('admin/layouts/admin_menu', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>
    <?php }else { ?>
            <?php echo $__env->make('admin/layouts/shop_menu', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>
    <?php }?>

    <!-- Menus generated by CRUD generator -->

</ul>
