{{getCurrentLang()}}
<ul id="menu" class="page-sidebar-menu">
    <?php
        $user = $user = Sentinel::getuser();
        if($user['type']*1 == 99){ ?>
            @include('admin/layouts/admin_menu')
    <?php }else { ?>
            @include('admin/layouts/shop_menu')
    <?php }?>

    <!-- Menus generated by CRUD generator -->

</ul>
